# Generated by Django 3.1.5 on 2021-02-17 14:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210217_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xs', 'X-Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X-Large')], max_length=11, null=True),
        ),
    ]
