# Generated by Django 3.1.5 on 2021-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210217_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
